version: '0.1.0'

services:
  house_grid:
    image: house_grid
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - BOT_TOKEN=
      - MAIN_DATABASE_URL=
      - HOME_ASSISTANT_HOST=
      - HOME_ASSISTANT_TOKEN=
